// Container-aware Code Mode transport.
//
// The shipped StdioCodeModeTransport writes the program to the HOST tmpdir and
// spawns `node <host-path>` — which cannot work when the sandbox is a Docker
// container (the path does not exist inside it). This transport speaks the
// SAME wire protocol (frames on stdout, rpc-results on stdin; runner source
// generated by the exported buildRunner/buildProgramModule), but stages the
// program inside the sandbox's bind-mounted working directory and runs it with
// `bun` (the unified sandbox image ships bun; the runner is plain node-API JS
// bun executes natively, TS program imports included).
//
// COMPILED-BEHAVIOR COUPLING (pinned @mastra/docker): the host↔container path
// mapping is read from the DockerSandbox instance's `_volumes`/`_workingDir`
// fields — plain JS fields, not in the .d.ts. Re-verify on every @mastra bump.
//
// EXIT RAMP: this transport exists only because the shipped transport stages
// on the host. When an upstream Mastra release makes StdioCodeModeTransport
// container-aware, DELETE this file and drop the transport argument in
// code-mode.ts. Upstream spawns `node --experimental-strip-types`, so that
// switch additionally requires node >= 22.6 in the unified sandbox image
// (deliberately not added yet — bun covers everything until then).
import { randomBytes } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  buildProgramModule,
  buildRunner,
  FRAME_PREFIX,
} from "@mastra/core/tools";
import type { WorkspaceSandbox } from "@mastra/core/workspace";

interface CodeModeRunOptions {
  abortSignal?: AbortSignal;
  dispatch: (toolId: string, args: unknown) => Promise<unknown>;
  onExternalCall?: (tool: string, args: unknown) => void;
  onExternalResult?: (
    tool: string,
    durationMs: number,
    error?: unknown
  ) => void;
  program: string;
  sandbox: WorkspaceSandbox;
  timeout: number;
  toolIds: string[];
}

interface CodeModeRunResult {
  error?: { message: string; name?: string };
  logs: string[];
  result?: unknown;
  success: boolean;
}

type Frame =
  | { type: "log"; message: string }
  | { type: "done"; ok: boolean; result?: unknown; error?: unknown }
  | { type: "rpc"; id: number; tool: string; args: unknown };

function sanitizeExternalName(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

/** Host staging dir + matching container dir for the sandbox workdir bind. */
function resolveSandboxPaths(
  sandbox: WorkspaceSandbox
): { containerDir: string; hostDir: string } | null {
  const fields = sandbox as unknown as {
    _volumes?: Record<string, string>;
    _workingDir?: string;
  };
  const volumes = fields._volumes;
  if (!volumes) {
    return null;
  }
  const workingDir = fields._workingDir;
  for (const [host, container] of Object.entries(volumes)) {
    if (!workingDir || container === workingDir) {
      return { containerDir: container, hostDir: host };
    }
  }
  return null;
}

export class DockerCodeModeTransport {
  async run(opts: CodeModeRunOptions): Promise<CodeModeRunResult> {
    const { sandbox, program, toolIds, dispatch, timeout, abortSignal } = opts;
    const processes = (
      sandbox as unknown as {
        processes?: {
          spawn: (
            command: string,
            options: {
              abortSignal?: AbortSignal;
              cwd?: string;
              onStdout?: (chunk: string) => void;
            }
          ) => Promise<{
            kill: () => Promise<unknown>;
            sendStdin: (data: string) => Promise<unknown>;
            wait: () => Promise<unknown>;
          }>;
        };
      }
    ).processes;
    if (!processes) {
      throw new Error("Code Mode requires a sandbox with process support");
    }
    const paths = resolveSandboxPaths(sandbox);
    if (!paths) {
      throw new Error(
        "Code Mode (docker transport) could not resolve the sandbox bind mount"
      );
    }
    // The container may not be running yet — the workspace starts it lazily
    // for EXECUTE_COMMAND; Code Mode must do the same. `start()` is race-safe.
    const lifecycle = sandbox as unknown as {
      start?: () => Promise<unknown>;
      status?: string;
    };
    if (lifecycle.status !== "running" && lifecycle.start) {
      await lifecycle.start();
    }

    const externals = toolIds.map((toolId) => ({
      externalName: sanitizeExternalName(toolId),
      toolId,
    }));
    const allowList = new Set(toolIds);
    const suffix = randomBytes(6).toString("hex");
    const hostDir = path.join(paths.hostDir, ".code-mode", suffix);
    const containerDir = path.posix.join(
      paths.containerDir,
      ".code-mode",
      suffix
    );
    await mkdir(hostDir, { recursive: true });
    const programName = "program.ts";
    const runnerName = "runner.mjs";
    await writeFile(
      path.join(hostDir, programName),
      buildProgramModule(program),
      "utf8"
    );
    await writeFile(
      path.join(hostDir, runnerName),
      buildRunner({
        externals,
        programModule: `file://${path.posix.join(containerDir, programName)}`,
      }),
      "utf8"
    );

    const logs: string[] = [];
    let done: CodeModeRunResult | undefined;
    let stdoutBuffer = "";
    let resolveDone: () => void = () => {
      // replaced below
    };
    const donePromise = new Promise<void>((resolve) => {
      resolveDone = resolve;
    });

    try {
      const handle = await processes.spawn(
        `bun ${path.posix.join(containerDir, runnerName)}`,
        {
          cwd: containerDir,
          ...(abortSignal ? { abortSignal } : {}),
          onStdout: (chunk: string) => {
            stdoutBuffer += chunk;
            let idx = stdoutBuffer.indexOf("\n");
            while (idx >= 0) {
              const line = stdoutBuffer.slice(0, idx);
              stdoutBuffer = stdoutBuffer.slice(idx + 1);
              if (line.startsWith(FRAME_PREFIX)) {
                try {
                  handleFrame(JSON.parse(line.slice(FRAME_PREFIX.length)));
                } catch {
                  // ignore malformed frame
                }
              }
              idx = stdoutBuffer.indexOf("\n");
            }
          },
        }
      );

      const respond = async (
        id: number,
        ok: boolean,
        result?: unknown,
        error?: { message: string; name?: string }
      ) => {
        await handle.sendStdin(
          `${JSON.stringify({ error, id, ok, result, type: "rpc-result" })}\n`
        );
      };

      const serveRpc = async (id: number, tool: string, args: unknown) => {
        const started = Date.now();
        opts.onExternalCall?.(tool, args);
        if (!allowList.has(tool)) {
          opts.onExternalResult?.(
            tool,
            Date.now() - started,
            new Error("not allowed")
          );
          await respond(id, false, undefined, {
            message: `Tool "${tool}" is not available in Code Mode`,
            name: "NotAllowedError",
          });
          return;
        }
        try {
          const result = await dispatch(tool, args);
          opts.onExternalResult?.(tool, Date.now() - started);
          await respond(id, true, result);
        } catch (error) {
          opts.onExternalResult?.(tool, Date.now() - started, error);
          await respond(id, false, undefined, {
            message: error instanceof Error ? error.message : String(error),
            ...(error instanceof Error ? { name: error.name } : {}),
          });
        }
      };

      const handleFrame = (frame: Frame) => {
        if (frame.type === "log") {
          logs.push(frame.message);
          return;
        }
        if (frame.type === "done") {
          done = frame.ok
            ? { logs, result: frame.result, success: true }
            : {
                error: frame.error as { message: string; name?: string },
                logs,
                success: false,
              };
          resolveDone();
          return;
        }
        void serveRpc(frame.id, frame.tool, frame.args).catch(() => {
          // rpc response failures surface as a hung call → run timeout
        });
      };

      let timer: NodeJS.Timeout | undefined;
      const timeoutPromise = new Promise<"timeout">((resolve) => {
        timer = setTimeout(() => resolve("timeout"), timeout);
      });
      const exitPromise = handle.wait().then(
        () => "exited" as const,
        () => "exited" as const
      );
      const outcome = await Promise.race([
        donePromise.then(() => "done" as const),
        exitPromise,
        timeoutPromise,
      ]);
      if (timer) {
        clearTimeout(timer);
      }
      if (outcome === "timeout") {
        await handle.kill().catch(() => {
          // best-effort
        });
        return {
          error: {
            message: `Code Mode execution timed out after ${timeout}ms`,
            name: "TimeoutError",
          },
          logs,
          success: false,
        };
      }
      if (!done) {
        await exitPromise;
      }
      return (
        done ?? {
          error: {
            message: "Program exited without returning a result",
            name: "NoResultError",
          },
          logs,
          success: false,
        }
      );
    } finally {
      await rm(hostDir, { force: true, recursive: true }).catch(() => {
        // best-effort cleanup
      });
    }
  }
}
