export {
  DockAuditLogsIcon,
  DockBankingIcon,
  DockChatbotIcon,
  DockChatIcon,
  DockContactsIcon,
  DockContextGraphIcon,
  DockDashboardIcon,
  DockEngentyIcon,
  DockExpensesIcon,
  DockInboxIcon,
  DockInvoicesIcon,
  DockKnowledgeBaseIcon,
  DockLeadsIcon,
  DockOffersIcon,
  DockPluginsIcon,
  DockProjectsIcon,
  DockSecretsIcon,
  DockSettingsIcon,
  DockSetupIcon,
  DockTeamMembersIcon,
  DockTimeTrackingIcon,
  DockUsersIcon,
  DockVaultIcon,
} from "@engenty/ui-icons";
