-- Drop module_secrets.service_secrets — never used.
--
-- Shipped in the module's baseline (20260716120000) as a (service_id, secret_id)
-- join, and carried an RLS policy reaching through `services` for the tenant.
-- Nothing ever read or wrote it: no TypeScript reference anywhere in the
-- workspace, no view, no function, no foreign key pointing at it, and zero rows.
-- Secret access is decided by owner_scope plus secret_grants and agent goal
-- grants (see secrets-sdk resolve.ts) — a service-to-secret join was designed
-- but never wired.
--
-- Found during the 2026-08-09 tenant-boundary audit: it has no tenant column of
-- its own, which for a live table would have meant the same composite-FK
-- treatment the other join tables got that day. Since it is dead, scoping it
-- would only have preserved a design nobody built. Drop it rather than leave a
-- table whose RLS policy implies an access path that does not exist.
--
-- docs/wip/secrets-vault-module.md still contains this DDL. That is a design
-- document describing the original plan, not a spec of the live schema, so it
-- is left as written.

drop table if exists module_secrets.service_secrets;
