export function getSourcesToolbarLabels(
  t: (key: string, options?: Record<string, unknown>) => string,
  total: number
) {
  return {
    searchPlaceholder: t("sources.search_placeholder"),
    display: t("display.display"),
    paginationSummary: t("sources.pagination_summary", { total }),
    sortByName: t("sources.sort_by_name"),
    sortByCreatedAt: t("list.sort_by_created_at"),
    sortByUpdatedAt: t("list.sort_by_updated_at"),
    sortByLastRun: t("sources.sort_by_last_run"),
    sortByNextRun: t("sources.sort_by_next_run"),
    ascending: t("display.ascending"),
    descending: t("display.descending"),
    compactView: t("display.compactView"),
    tableView: t("display.tableView"),
    cardsView: t("display.cardsView"),
    sortBy: t("display.sortBy"),
    displayedColumns: t("display.displayedColumns"),
    hiddenInTable: t("display.hiddenInTable"),
    showAll: t("display.showAll"),
    hideAll: t("display.hideAll"),
    noColumnsDisplayed: t("display.noColumnsDisplayed"),
    name: t("sources.name"),
    adapter: t("sources.adapter"),
    status: t("sources.status"),
    lastRun: t("sources.last_run"),
    nextRun: t("sources.next_run"),
    createdAt: t("columns.created_at"),
    updatedAt: t("columns.updated_at"),
    statusFilterAll: t("sources.filter_status_all"),
    filterActive: t("sources.filter_active"),
    filterPaused: t("sources.filter_paused"),
    filterFailed: t("sources.filter_failed"),
    clearFilters: t("sources.clear_filters"),
    clearSelection: t("sources.clear_selection"),
  };
}
