/* AUTO-GENERATED FILE. DO NOT EDIT. */
import type { UiPluginCatalogEntry } from "./catalog";
import { createGeneratedUiPluginCatalogEntry } from "./runtime-ui-loader";

export const uiPluginCatalog: UiPluginCatalogEntry[] = [
  createGeneratedUiPluginCatalogEntry({ pluginId: "auth-ui", importPath: "@engenty/auth-ui/plugin", exportName: "default", loadModule: async () => await import("@engenty/auth-ui/plugin"), loadStatic: async () => (await import("@engenty/auth-ui/plugin")).default, optionalPluginIds: [], sourceInfo: {"pluginId":"auth-ui","packageName":"@engenty/auth-ui","version":"0.0.1","sourceType":"package","rootDir":"packages/auth-ui","source":"@engenty/auth-ui/plugin","manifestPath":"packages/auth-ui/engenty.plugin.json","manifestId":"auth-ui","registrationKind":"ui.plugin"} }),
  createGeneratedUiPluginCatalogEntry({ pluginId: "user-management-ui", importPath: "@engenty/user-management-ui/plugin", exportName: "default", loadModule: async () => await import("@engenty/user-management-ui/plugin"), loadStatic: async () => (await import("@engenty/user-management-ui/plugin")).default, optionalPluginIds: [], sourceInfo: {"pluginId":"user-management-ui","packageName":"@engenty/user-management-ui","version":"0.0.1","sourceType":"package","rootDir":"packages/user-management-ui","source":"@engenty/user-management-ui/plugin","manifestPath":"packages/user-management-ui/engenty.plugin.json","manifestId":"user-management-ui","registrationKind":"ui.plugin"} }),
  createGeneratedUiPluginCatalogEntry({ pluginId: "ai-ui", importPath: "@engenty/ai-ui/plugin", exportName: "default", loadModule: async () => await import("@engenty/ai-ui/plugin"), loadStatic: async () => (await import("@engenty/ai-ui/plugin")).default, optionalPluginIds: [], sourceInfo: {"pluginId":"ai-ui","packageName":"@engenty/ai-ui","version":"0.0.1","sourceType":"package","rootDir":"packages/ai-ui","source":"@engenty/ai-ui/plugin","manifestPath":"packages/ai-ui/engenty.plugin.json","manifestId":"ai-ui","registrationKind":"ui.plugin"} }),
  createGeneratedUiPluginCatalogEntry({ pluginId: "audit-logs", importPath: "@engenty/audit-logs/plugin", exportName: "default", loadModule: async () => await import("@engenty/audit-logs/plugin"), loadStatic: async () => (await import("@engenty/audit-logs/plugin")).default, optionalPluginIds: [], sourceInfo: {"pluginId":"audit-logs","packageName":"@engenty/audit-logs","version":"0.0.1","sourceType":"package","rootDir":"packages/audit-logs","source":"@engenty/audit-logs/plugin","manifestPath":"packages/audit-logs/engenty.plugin.json","manifestId":"audit-logs","registrationKind":"ui.plugin"} }),
  createGeneratedUiPluginCatalogEntry({ pluginId: "context-graph", importPath: "@engenty/context-graph/plugin", exportName: "default", loadModule: async () => await import("@engenty/context-graph/plugin"), loadStatic: async () => (await import("@engenty/context-graph/plugin")).default, optionalPluginIds: [], sourceInfo: {"pluginId":"context-graph","packageName":"@engenty/context-graph","version":"0.0.1","sourceType":"package","rootDir":"packages/context-graph","source":"@engenty/context-graph/plugin","manifestPath":"packages/context-graph/engenty.plugin.json","manifestId":"context-graph","registrationKind":"ui.plugin"} }),
  createGeneratedUiPluginCatalogEntry({ pluginId: "engenty-copilot", importPath: "@engenty/engenty-copilot/ui/plugin", exportName: "default", loadModule: async () => await import("@engenty/engenty-copilot/ui/plugin"), loadStatic: async () => (await import("@engenty/engenty-copilot/ui/plugin")).default, optionalPluginIds: [], sourceInfo: {"pluginId":"engenty-copilot","packageName":"@engenty/engenty-copilot","version":"0.0.1","sourceType":"module","rootDir":"modules/engenty-copilot","source":"@engenty/engenty-copilot/ui/plugin","manifestPath":"modules/engenty-copilot/engenty.plugin.json","manifestId":"engenty-copilot","registrationKind":"ui.plugin"} }),
];
