import type { UiPluginCatalogEntry } from "./catalog";

// GENERATED by oss-spike-assemble.mjs — public (unauthenticated) UI plugins,
// filtered to the modules in this cut.
export const publicUiPluginCatalog: UiPluginCatalogEntry[] = [

];
