/**
 * Default CSS selectors removed before HTML→Markdown to drop common chrome
 * (headers, footers, nav, sidebars, ads). Conservative list — avoids overly
 * broad patterns like `[class*="ad"]` that match unrelated class names.
 */
export const DEFAULT_HTML_EXCLUDE_SELECTORS: readonly string[] = [
  "header",
  "footer",
  "nav",
  "aside",
  '[role="banner"]',
  '[role="navigation"]',
  '[role="contentinfo"]',
  '[role="complementary"]',
  '[role="search"]',
  ".site-header",
  ".site-footer",
  ".page-header",
  ".page-footer",
  "#header",
  "#footer",
  "#nav",
  "#navigation",
  "#sidebar",
  ".navbar",
  ".nav-bar",
  ".sidebar",
  ".advertisement",
  ".google-auto-placed",
  ".gpt-ad",
  "#BorlabsCookieBox",
  ".BorlabsCookie",
  "[data-borlabs-cookie]",
  '[class*="Borlabs"]',
  '[class*="borlabs"]',
  '[class*="_brlbs"]',
  '[id*="Borlabs"]',
  '[id*="borlabs"]',
  '[id*="_brlbs"]',
  ".borlabs-cookie",
  ".borlabs-cookie-preference",
  ".borlabs-cookie-notice",
  "#CookieBox",
  "#CookieConsent",
  "#CookiebotWidget",
  "#CybotCookiebotDialog",
  "#onetrust-banner-sdk",
  "#onetrust-consent-sdk",
  ".cc-window",
  ".cc-banner",
  ".cc_dialog",
  ".cmplz-cookiebanner",
  ".cky-consent-container",
  ".cookie-consent",
  ".cookie-consent-banner",
  ".cookie-notice",
  ".cookie-settings",
  ".cookiebot",
  ".consent-manager",
  ".consent-modal",
  ".privacy-settings",
  '[aria-label*="cookie" i]',
  '[aria-label*="cookies" i]',
  '[aria-label*="consent" i]',
  '[aria-label*="datenschutz" i]',
  '[class*="CookieBanner"]',
  '[class*="CookieConsent"]',
  '[class*="cookie-consent"]',
  '[class*="cookie-banner"]',
  '[class*="cookie-notice"]',
  '[class*="cookie-settings"]',
  '[class*="consent-manager"]',
  '[class*="consent-modal"]',
  '[class*="privacy-settings"]',
  '[id*="CookieBanner"]',
  '[id*="CookieConsent"]',
  '[id*="cookie-banner"]',
  '[id*="cookie-consent"]',
  '[id*="cookie-notice"]',
  '[id*="cookie-settings"]',
  '[class*="consent-banner"]',
  '[id*="consent"]',
];
