import { describe, expect, it } from "vitest";
import { renderExampleFile } from "./env-example-render.js";
import { parseEnvDocument, serializeEnvDocument } from "./env-file-document.js";

describe("renderExampleFile", () => {
  it("renders the root template with required keys uncommented", () => {
    const text = renderExampleFile("root");
    expect(text).toContain("ENGENTY_SECURITY_JWT_SECRET=");
    expect(text).toContain("SUPABASE_URL=http://127.0.0.1:54321");
    expect(text).toContain("SUPABASE_SERVICE_ROLE_KEY=sb_secret_...");
    // Optional vars render commented out.
    expect(text).toContain("# LANGFUSE_SECRET_KEY=");
    // Generated-file header present.
    expect(text).toContain("Generated by `engenty env example`");
  });

  it("requires the UI's Supabase values locally but not in a deployment", () => {
    // A deployment's gateway writes them into the served page from
    // SUPABASE_URL / SUPABASE_ANON_KEY; `pnpm dev` has no gateway, so Vite
    // needs them in the root file.
    expect(renderExampleFile("root")).toMatch(/^VITE_SUPABASE_URL=/m);
    expect(renderExampleFile("deploy")).toMatch(/^# VITE_SUPABASE_URL=/m);
    expect(renderExampleFile("deploy")).toMatch(/^# VITE_SUPABASE_ANON_KEY=/m);
  });

  it("keeps dev URLs as an informational comment block", () => {
    const text = renderExampleFile("root");
    expect(text).toContain("pnpm dev:urls:localhost");
    expect(text).toContain("pnpm dev:urls:portless");
    expect(text).toContain("# ENGENTY_API_BASE_URL=");
    // Dev URL keys must never be uncommented in the template.
    expect(text).not.toMatch(/^ENGENTY_API_BASE_URL=/m);
  });

  it("renders Vite vars in the root template (Vite envDir is the workspace root)", () => {
    const text = renderExampleFile("root");
    expect(text).toContain("VITE_SUPABASE_URL=http://127.0.0.1:54321");
    expect(text).toContain("VITE_SUPABASE_ANON_KEY=sb_publishable_...");
    expect(text).not.toContain("PUBLIC_APP_URL");
    // Retired integrations stay out.
    expect(text).not.toContain("CONVEX");
    expect(text).not.toContain("VITE_SYNC_BEARER_TOKEN");
    expect(text).not.toContain("POWERSYNC_API_URL");
    expect(text).not.toContain("VITE_MANAGE_APP_BASE");
    expect(text).not.toContain("VITE_MANAGE_BASE_URL");
    expect(text).not.toContain("ENGENTY_MANAGE_BASE_URL");
    expect(text).not.toContain("ENGENTY_GATEWAY_MANAGE_ENABLED");
    expect(text).not.toContain("DAYTONA_API_URL");
    expect(text).not.toContain("DAYTONA_API_KEY");
  });

  it("renders the deploy template with production keys", () => {
    const text = renderExampleFile("deploy");
    expect(text).toContain("PUBLIC_APP_URL=https://app.example.com");
    expect(text).toContain(
      "ENGENTY_SANDBOX_DOCKER_IMAGE=engenty-sandbox:latest"
    );
    expect(text).toContain("ENGENTY_SECURITY_JWT_SECRET=");
    // SUPABASE_DB_URL is in the deploy template — the migrate init-service
    // needs a direct Postgres connection to apply migrations automatically.
    expect(text).toContain("SUPABASE_DB_URL");
  });

  it("renders templates the document model parses cleanly (round-trip)", () => {
    for (const scope of ["root", "deploy"] as const) {
      const text = renderExampleFile(scope);
      const doc = parseEnvDocument(text);
      expect(serializeEnvDocument(doc)).toBe(text);
    }
  });

  it("is deterministic", () => {
    expect(renderExampleFile("root")).toBe(renderExampleFile("root"));
  });
});
