import { manifestForScope } from "./env-manifest.js";
import {
  defaultValueForScope,
  type EnvScope,
  type EnvVarSpec,
  requirementForScope,
} from "./env-manifest-types.js";

const GENERATED_HEADER = [
  "# Generated by `engenty env example` from packages/cli/src/env-setup/env-manifest.ts.",
  "# Edit the manifest, then run: pnpm env:example:write — do not edit this file by hand.",
  "# Interactive setup: pnpm engenty env init",
];

const SCOPE_NOTES: Partial<Record<EnvScope, string[]>> = {
  deploy: [
    "# Copy to deploy/.env and set values before:",
    "# docker compose -f deploy/docker-compose.yaml --env-file deploy/.env up -d",
    "# Full guide: deploy/DEPLOY.md",
  ],
  root: [
    "# Copy to .env.local (or run pnpm engenty env init). Production values live in deploy/.env.example.",
  ],
};

function templateValue(spec: EnvVarSpec, scope: EnvScope): string {
  return defaultValueForScope(spec, scope) ?? spec.exampleValue ?? "";
}

function renderVar(
  spec: EnvVarSpec,
  scope: EnvScope,
  seenInstructions: Set<string>
): string[] {
  const lines: string[] = [];
  lines.push(`# ${spec.description}`);
  if (spec.obtain.kind === "provider") {
    // Vars sharing a provider (e.g. OAuth id + secret) get the steps once.
    if (!seenInstructions.has(spec.obtain.url)) {
      seenInstructions.add(spec.obtain.url);
      lines.push(`# ${spec.obtain.url}`);
      for (const step of spec.obtain.instructions) {
        lines.push(`#   ${step}`);
      }
    }
  } else if (spec.obtain.kind === "manual" && spec.obtain.instructions) {
    for (const step of spec.obtain.instructions) {
      lines.push(`#   ${step}`);
    }
  }
  const assignment = `${spec.key}=${templateValue(spec, scope)}`;
  lines.push(
    requirementForScope(spec, scope) === "optional"
      ? `# ${assignment}`
      : assignment
  );
  return lines;
}

function renderDevUrlsGroup(specs: EnvVarSpec[]): string[] {
  // Mirrors the block written by scripts/sync-dev-env-localhost.mjs (informational).
  const lines = [
    "# ── Dev URLs (generated block — pnpm dev:urls:localhost or pnpm dev:urls:portless) ──",
    "# Default: http://localhost:5173 (Vite). Optional HTTPS: docs/dev/portless-local-urls.md",
  ];
  for (const spec of specs) {
    lines.push(`# ${spec.key}=`);
  }
  return lines;
}

export function renderExampleFile(
  scope: EnvScope,
  workspaceRoot?: string
): string {
  const specs = manifestForScope(scope, workspaceRoot);
  const seenInstructions = new Set<string>();
  const blocks: string[][] = [[...GENERATED_HEADER]];
  const scopeNote = SCOPE_NOTES[scope];
  if (scopeNote) {
    blocks.push([...scopeNote]);
  }

  const seenGroups: string[] = [];
  const byGroup = new Map<string, EnvVarSpec[]>();
  for (const spec of specs) {
    if (!byGroup.has(spec.group)) {
      seenGroups.push(spec.group);
      byGroup.set(spec.group, []);
    }
    byGroup.get(spec.group)?.push(spec);
  }

  for (const group of seenGroups) {
    const groupSpecs = byGroup.get(group) ?? [];
    if (groupSpecs.every((spec) => spec.obtain.kind === "portless")) {
      blocks.push(renderDevUrlsGroup(groupSpecs));
      continue;
    }
    const lines = [`# ── ${group} ──`];
    for (const spec of groupSpecs) {
      lines.push("", ...renderVar(spec, scope, seenInstructions));
    }
    blocks.push(lines);
  }

  return `${blocks.map((block) => block.join("\n")).join("\n\n")}\n`;
}
