export {
  collectFileStorageExplorerIds,
  fileStorageExplorerPathLabel,
  fileStorageExplorerSegments,
  isFileStorageUuidSegment,
  isNativeFileSpaceObjectKey,
  isSpaceFolderExplorerPrefix,
  labelFileStorageExplorerSegments,
  overlayExplorerFolderName,
  spaceIdFromFileStorageExplorerPath,
} from "./explorer-labels.js";
export type {
  FileEntryRow,
  FileEntryStatus,
  FileFolderRow,
  FileSource,
  FileSourceContentInput,
  FileSourceContext,
  FileSourceFile,
  FileSourceFolder,
  FileSourceKind,
  FileSourceListing,
  FileSourceListOptions,
  FileSourceUploadInput,
  FileSourceUploadTicket,
  FileSpaceOwner,
  NativeBlobStore,
  NativeEntryCreateInput,
  NativeEntryPatch,
  NativeEntryStore,
  NativeFolderCreateInput,
  NativeFolderPatch,
  NativeFolderStore,
} from "./file-source-types.js";
export {
  FILE_SPACE_OWNER_KINDS,
  FILE_SPACE_QUERY_ROOT,
  type FileSpaceOwnerKind,
  type FileSpaceOwnerRef,
  fileSpaceDriveQueryKey,
  fileSpaceInvalidationKey,
  fileSpaceListingQueryKey,
  fileSpaceOwnerKey,
  fileSpaceOwnerPath,
  isFileSpaceOwnerKind,
  parseFileSpaceOwnerKey,
  projectFileSpaceOwner,
  spaceFileSpaceOwner,
} from "./file-space-owner.js";
export {
  type CreateFileStorageServiceOptions,
  createFileStorageService,
  guessFileStorageMimeFromFilename,
} from "./file-storage-service.js";
export type {
  FileStorageFile,
  FileStorageListOptions,
  FileStorageListResult,
  FileStorageProvider,
  FileStorageService,
  FileStorageSignedUploadOptions,
  FileStorageSignedUploadResult,
  FileStorageUploadOptions,
  FileStorageUrlOptions,
} from "./file-storage-types.js";
export {
  FILE_STORAGE_ROOT_SEGMENT,
  FILE_STORAGE_SPACES_SEGMENT,
  fileStorageSpaceObjectKey,
  fileStorageSpacePrefix,
  fileStorageTenantObjectKey,
  inboxMessageIdFromFileStorageKey,
  knowledgeBaseSlugFromFileStorageKey,
  knowledgePathLabelFromFileStorageKey,
  moduleFolderFromFileStorageKey,
  type ParsedFileStorageSpaceKey,
  parseFileStorageSpaceObjectKey,
  pathSegmentsAfterFileStorageContainerRoot,
  pathSegmentsAfterFileStorageTenantRoot,
} from "./internal-storage-path.js";
export {
  FILE_STORAGE_OFFICE_PDF_PREVIEW_MIME_TYPES,
  isFileStorageOfficePdfPreviewMime,
  isFileStorageThumbnailSourceMime,
} from "./office-preview-mime.js";
export { createSupabaseFileStorageProvider } from "./providers/supabase-provider.js";
export {
  type CreateNativeFileSourceOptions,
  createNativeFileSource,
  FileSourceConflictError,
  FileSourceNotFoundError,
  FileSourceReadOnlyError,
} from "./sources/native-file-source.js";
export {
  buildSpaceDrive,
  type DriveNode,
  type DriveNodeKind,
  type SpaceDriveArtifact,
  type SpaceDriveDataEntry,
  type SpaceDriveDataFolder,
  type SpaceDriveDataRoot,
  type SpaceDriveFile,
  type SpaceDriveFolder,
  type SpaceDriveInput,
  type SpaceDriveProject,
  spaceDataChildNodes,
  spaceDataRootNodes,
  spaceDriveProjectNodes,
  spaceDriveRootOwner,
  spaceFolderChildNodes,
} from "./space-drive.js";
export {
  assertTenantScopedStorageKey,
  FileStorageTenantScopeError,
} from "./tenant-storage-key.js";
export {
  FILE_STORAGE_TEXT_PREVIEW_MIME_TYPES,
  isFileStorageCsvMime,
  isFileStorageMarkdownMime,
  isFileStoragePdfMime,
  isFileStorageSpreadsheetMime,
  isFileStorageTextPreviewMime,
  resolveFileStoragePreviewMime,
} from "./text-preview-mime.js";
export {
  COMMONS_STORAGE_PREFIX,
  type ParsedWorkWorkspacePrefix,
  parseWorkWorkspacePrefix,
  type WorkContainerTier,
  workWorkspacePrefix,
  workWorkspaceRelativePrefix,
} from "./work-workspace.js";
