export {
  DetailPageHeader,
  type DetailPageHeaderProps,
} from "./detail-page-header";
export type { Profile as AvatarStackProfile } from "./shell/avatar-stack";
export { AvatarStack } from "./shell/avatar-stack";
export {
  BrandLogoMark,
  type BrandLogoMarkProps,
  brandLogoInitials,
} from "./shell/brand-logo-mark";
export {
  type BreadcrumbContextMetaRow,
  BreadcrumbContextPicker,
  type BreadcrumbContextPickerProps,
} from "./shell/breadcrumb-context-picker";
export {
  type ContextPopoverFooter,
  type ContextPopoverItem,
  ContextPopoverList,
  type ContextPopoverListProps,
  type ContextPopoverOpenOn,
  type ContextPopoverRenderLink,
  type ContextPopoverSection,
} from "./shell/context-popover-list";
export {
  ShellBreadcrumbPlainText,
  type ShellBreadcrumbPlainTextMode,
} from "./shell/shell-breadcrumb-plain-text";
export {
  computeShellBreadcrumbCompactCollapsed,
  type ShellBreadcrumbCompactOptions,
  type ShellBreadcrumbItem,
  type ShellBreadcrumbRenderLink,
  ShellBreadcrumbTrail,
  type ShellBreadcrumbTrailProps,
  type ShellBreadcrumbTruncateEllipsis,
  type ShellBreadcrumbTruncateOverflow,
  type ShellBreadcrumbVariant,
} from "./shell/shell-breadcrumb-trail";
export {
  readerBlendTopbarActionButtonClassName,
  TopbarActionLabel,
  topbarIconButtonClassName,
} from "./shell/topbar-action-label";
export {
  attachSidebarListInsertDropHandlers,
  capSidebarForest,
  computeSidebarListInsertPlace,
  filterSidebarForest,
  SIDEBAR_ROW_INDENT_BASE_PX,
  SIDEBAR_ROW_INDENT_STEP_PX,
  SidebarContent,
  SidebarExpandChevronButton,
  type SidebarExpandChevronButtonProps,
  type SidebarForest,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarListInsertDropBar,
  type SidebarListInsertDropHandlersArgs,
  type SidebarListInsertDropTarget,
  type SidebarListInsertPlace,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarNavList,
  SidebarNavSectionLabel,
  SidebarRow,
  SidebarRowActions,
  type SidebarRowActionsProps,
  SidebarRowButton,
  type SidebarRowButtonProps,
  SidebarRowLeadingIcon,
  type SidebarRowLeadingIconProps,
  type SidebarRowProps,
  SidebarSectionLabel,
  type SidebarSectionLabelProps,
  SidebarTab,
  SidebarTabStrip,
  sidebarColumnContentInsetClassName,
  sidebarColumnContentInsetEndClassName,
  sidebarColumnGutterClassName,
  sidebarDenseMenuContentClassName,
  sidebarDenseMenuIconClassName,
  sidebarDenseMenuItemClassName,
  sidebarDenseMenuLabelClassName,
  sidebarForestSome,
  sidebarLeadingIconSlotClassName,
  sidebarMenuButtonVariants,
  sidebarRowActionsOverlayClassName,
  sidebarRowPaddingLeftPx,
  sidebarSectionLabelPlAlignToRootRowIconClassName,
  sidebarSectionLabelPlAlignToRowIconClassName,
} from "./sidebar";
