// Wizard copy, English.

import type { SetupCopy } from "./setup-wizard-i18n";

export const setupCopyEn: SetupCopy = {
  saving: "Saving…",
  footer: `© ${new Date().getFullYear()} Engenty`,
  theme: { light: "Light mode", dark: "Dark mode" },
  progress: {
    platformTitle: "Platform",
    platform: ["Account", "AI"],
    teamTitle: "Getting started",
    team: ["Copilot", "Space", "Engenty", "Setup", "Apps"],
  },
  welcome: {
    title: "Welcome to engenty",
    lead: "Two short steps before your team moves in: the administrator account and the AI every engenty thinks with.",
    checking: "Checking the installation…",
    allGood: (count) => `Installation ready · ${count} checks passed`,
    needsYou: (count) =>
      count === 1
        ? "One thing needs your terminal"
        : `${count} things need your terminal`,
    polling: "Run the command below. This page checks again every few seconds.",
    readFailed: "The installation can't be read right now.",
    details: "Show checks",
    hideDetails: "Hide checks",
    recheck: "Check again",
    rowStatus: { ok: "ok", blocks: "blocks", later: "later" },
    start: "Let's go",
  },
  admin: {
    title: "Create the superadmin account",
    lead: "You're the first person here, so you look after the installation.",
    name: "Your name",
    namePlaceholder: "Jane Doe",
    email: "Email",
    emailPlaceholder: "jane@company.com",
    password: "Password",
    passwordPlaceholder: "At least 6 characters",
    show: "Show password",
    hide: "Hide password",
    strength: { weak: "Weak", medium: "Medium", strong: "Strong" },
    submit: "Create account",
    busy: "Creating your account…",
    errors: {
      name: "Enter your name.",
      email: "Enter a valid email address.",
      password: "Use at least 6 characters.",
    },
  },
  provider: {
    title: "Connect the AI",
    lead: "Every engenty thinks with the models behind this key. It stays on the server.",
    recommended: "Recommended",
    more: (count) => `${count} more providers`,
    fewer: "Fewer providers",
    keyLabel: "API key",
    getKey: "Get a key",
    keyNote: "Stored as a platform setting and never shown again.",
    test: "Test",
    testing: "Testing…",
    valid: (models) =>
      models ? `Key works: ${models} models available` : "Key works",
    invalid: "This key doesn't work. Check it and try again.",
    submit: "Continue",
    busy: "Connecting…",
    skip: "Set up later. Until then your engenties can't answer.",
    needKey: "Paste a key, or set it up later.",
    pasteFirst: "Paste the key first.",
    blurbs: {
      vercel: "One key for every model: chat, search, images and voice.",
      openrouter:
        "Chat models from every vendor. Search and voice need Vercel.",
      opper: "EU-hosted gateway for chat models.",
      openai: "OpenAI's chat models on your own account.",
      anthropic: "Claude models on your own account.",
    },
  },
  copilot: {
    title: "Your copilot",
    lead: "Always on your side. Your personal assistant. Shows you around. Takes on whatever you hand it.",
    look: "Its look",
    find: "You'll always find it in the app bar.",
    shortcut: "open from anywhere",
    voiceShortcut: "talk to it",
    greeting: (name) =>
      `Hi ${name}! I'm your copilot. You'll find me in the app bar, wherever you are.`,
    submit: "Continue",
    busy: "Saving…",
  },
  space: {
    title: "Your first space",
    lead: "Organise your work in spaces: a client, a team, a topic. Your team, engenties and apps work there together.",
    name: "Name",
    namePlaceholder: "e.g. Clients, Marketing, Research",
    color: "Colour",
    icon: "Icon",
    initials: "Initials",
    privacy: "Who can see it",
    visibility: {
      open: { label: "Open", hint: "Everyone in your team sees the space." },
      private: {
        label: "Private",
        hint: "Only the members you add see the space.",
      },
    },
    required: "Give the space a name.",
    submit: "Create space",
    busy: "Creating…",
  },
  engenty: {
    title: "Your first engenty",
    lead: "An engenty stays in the space: visible to everyone in it, always available. It takes on the recurring work and keeps going, even while you're away.",
    look: "Look",
    name: "Name",
    defaultName: "Chief of Staff",
    job: "What should it do?",
    defaultJob:
      "Sets the space up, routes the work, and brings in a teammate when a job deserves its own owner.",
    jobHint: "One or two sentences. It grows into the role from there.",
    required: "Give your engenty a name.",
    submit: "Hire",
    busy: "Hiring…",
    skip: "Hire later",
  },
  setup: {
    title: "The space's computer",
    lead: "Every space has its own computer, with a browser. Decide what its engenties may do there.",
    browserHint:
      "Engenties work on the web here. You watch live and can take over any time.",
    caption: "The space's browser · logins stay in the space",
    autostart: "Start without asking",
    unattended: "Usable unattended",
    autostartState: {
      on: "Engenties start it themselves.",
      off: "Engenties ask before starting it.",
    },
    unattendedState: {
      on: "Routines use it without you.",
      off: "Routines stop and ask.",
    },
    approval: "Approvals",
    approvalChoice: {
      manual: {
        label: "Manual",
        hint: "They ask before anything risky, and whenever an action needs a yes.",
      },
      auto: {
        label: "Auto",
        hint: "Small things run. Anything risky waits for your yes.",
      },
      "pass-all": {
        label: "Let all through",
        hint: "They never ask, and still only do what they're allowed to.",
      },
    },
    submit: "Continue",
    busy: "Saving…",
  },
  apps: {
    title: "Your first apps",
    lead: "Apps bring tools into the space, for you, your team and your engenties. Pick one to start with.",
    cards: {
      build: {
        label: "Engenty Apps",
        hint: "Do something else. Ask engenties to build your workflows and apps.",
      },
      knowledge: {
        label: "Knowledge base",
        hint: "Articles, guides and answers everyone can use.",
      },
      contacts: {
        label: "Contacts",
        hint: "Clients, partners and suppliers in one place.",
      },
      commercial: {
        label: "Commercial",
        hint: "Offers, invoices and receipts.",
      },
    },
    items: {
      "engenty-apps": "Engenty Apps",
      "knowledge-base": "Knowledge base",
      contacts: "Contacts",
      offers: "Offers",
      invoices: "Invoices",
      expenses: "Receipts",
    },
    later: "Add more apps any time in the space settings.",
    submit: "Add app",
    busy: "Adding…",
    skip: "Continue without apps",
  },
  ready: {
    titleFor: (space) => `${space} is ready`,
    leadWith: (engenty) => `${engenty} has already said hello in the space.`,
    leadWithout: "Your copilot is waiting for you.",
    appsRow: (names) =>
      names.length === 0 ? "No apps yet" : `Apps: ${names.join(", ")}`,
    spaceRow: (name, path) => `${name} · ${path}`,
    engentyRow: (name) => `${name} works in the space`,
    engentySkipped: "No engenty yet. Hire one from the space.",
    copilotStarting: "Your copilot is getting ready…",
    copilotReady: "Your copilot is ready",
    copilotLater: "Your copilot starts when you first open it",
    openSpace: "Open the space",
    signingIn: "Signing you in…",
  },
  scene: {
    captions: {
      welcome: {
        kicker: "engenty",
        line: "People and AI teammates, working side by side in spaces.",
      },
      admin: {
        kicker: "Platform",
        line: "Engenty is a multi-user platform. As superadmin, you look after the installation.",
      },
      provider: {
        kicker: "The AI",
        line: "Every engenty thinks with the models behind this key.",
      },
      copilot: {
        kicker: "Copilot",
        line: "Yours alone. Live when you are.\nIn every space.",
      },
      space: {
        kicker: "Spaces",
        line: "One place per purpose.\nOnly its apps, only its people.",
      },
      engenty: {
        kicker: "Engenties",
        line: "They stay in the space and keep working when you log off.",
      },
      setup: {
        kicker: "Computer",
        line: "Its own computer, with a browser.\nLogins stay in the space.",
      },
      apps: {
        kicker: "Apps",
        line: "Only the apps it needs.\nFor people and engenties alike.",
      },
      ready: {
        kicker: "Ready",
        line: "Your space is set up.\nAnd someone's already waiting.",
      },
    },
    tabs: { work: "Work", data: "Data" },
    apps: "Apps",
    engenties: "Engenties",
    copilot: "Copilot",
    admin: "Admin",
    runsOn: (label) => `on ${label}`,
    live: "live · with you everywhere",
    openAsk: "Show me the Q4 proposal for ACME",
    opened: "Here it is, open on the right.",
    paneTitle: "Q4 proposal · ACME",
    paneBadge: "Draft",
    voiceSaid: "“What's on for today?”",
    modes: {
      window: "Window",
      sidebar: "Sidebar",
      full: "Full screen",
      voice: "Voice",
    },
    noModel: "asleep · no model yet",
    composer: "Message…",
    computer: {
      screenCaption: (engenty) => `${engenty}'s browser`,
      autostart: "Start without asking",
      unattended: "Usable unattended",
      routines: "Routines",
      noRoutines: "No routines. It works when you talk to it.",
      connections: "Connections",
      connectionsHint: "Outside services this agent can reach.",
      connect: "Connect",
      noConnections: "No connections.",
      tab: "mywebsite.com",
      url: "https://mywebsite.com/",
      takeOver: "Take over",
      driving: "An engenty is driving",
      signIn: "Sign in",
      email: "Email",
      password: "Password",
      emailValue: "alex@kaiser.design",
      fetch: "I'll check what's new on mywebsite.com.",
      card: {
        title: "Sign in to mywebsite.com",
        goesTo: "Goes straight into the page on",
        private:
          "What you type only lands in the page. The engenty never sees it, and it isn't stored.",
        fill: "Fill into the page",
        decline: "Not now",
      },
      askStart: "May I start the browser for that?",
      start: "Start",
      notNow: "Not now",
    },
    scopeSpace: "Space",
    desk: {
      open: "Open",
      role: "Coordinator: reports to nobody, may hire and set up",
      readable: (space) => `Readable by everyone in ${space}.`,
      effort: "Normal",
      approval: (mode) => `Default: ${mode}`,
      toolUsed: "1 tool used",
    },
    build: {
      ask: "Make me a routine: every Monday, a weekly report for the team.",
      reply: "Sure. Here's how it would run.",
      workflow: {
        title: "Weekly report",
        schedule: "Routine · every Monday, 8:00",
        steps: [
          "Collect the week's tasks",
          "Ask you what goes in",
          "Write the report",
          "Send it to the team",
        ],
        cancel: "Cancel",
        run: "Try it now",
      },
      wizard: {
        step: "1 / 2",
        question: "What goes into this week's report?",
        choices: ["Everything that got done", "Client projects only"],
      },
      done: {
        title: "Done",
        summary: "The weekly report is written and open next to you.",
        open: "Open the routine",
      },
      result: { title: "Weekly report · Week 40", badge: "Draft" },
    },
    appView: {
      build: {
        nav: ["Apps", "Workflows"],
        rows: [
          { name: "Leave planner", by: "Chief of Staff" },
          { name: "Offer calculator", by: "Chief of Staff" },
          { name: "Weekly report", by: "Chief of Staff" },
        ],
        newApp: "New app: ask an engenty",
      },
      knowledge: {
        nav: ["Articles", "Categories", "FAQ"],
        rows: ["Client onboarding", "Offer process", "Style guide", "Time off"],
      },
      contacts: {
        nav: ["All", "Clients", "Partners", "Suppliers"],
        rows: [
          { name: "Julia Berger", company: "ACME Ltd" },
          { name: "Tom Weiss", company: "Nordwind Inc" },
          { name: "Sara Klein", company: "Studio Blau" },
          { name: "Max Huber", company: "Huber & Sons" },
        ],
      },
      commercial: {
        nav: ["Offers", "Invoices", "Receipts"],
        rows: [
          {
            number: "OF-014",
            customer: "ACME Ltd",
            amount: "€ 12,400",
            status: "draft",
          },
          {
            number: "OF-013",
            customer: "Nordwind Inc",
            amount: "€ 3,850",
            status: "sent",
          },
          {
            number: "OF-012",
            customer: "Studio Blau",
            amount: "€ 7,200",
            status: "accepted",
          },
        ],
        status: { draft: "Draft", sent: "Sent", accepted: "Accepted" },
      },
    },
    composerTo: (engenty) => `Message ${engenty}…`,
    engentyAsk: "Draft the Q4 offer for ACME.",
    engentyDone: "Done. The draft is open next to us.",
    engentyGreeting: (engenty, space) =>
      `Hi, I'm ${engenty}, new in ${space}. Tell me what's coming up and I'll take it from there.`,
    spaceFallback: "Your space",
  },
};
